version: 2
updates:

- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: "Europe/London"
  open-pull-requests-limit: 99
  reviewers:
  - credfeto
  assignees:
  - credfeto
  allow:
  - dependency-type: all
  ignore:
  - dependency-name: "Yoti"
  - dependency-name: "Microsoft.*"
  - dependency-name: "FunFair.*"
  - dependency-name: "Octopus.*"
  commit-message:
    prefix: "[FF-1429]"
  rebase-strategy: "auto"
  labels:
  - "dotnet"
  - "dependencies"
  - "Changelog Not Required"

