version: 1
update_configs:
  - package_manager: "github_actions"
    directory: "/"
    update_schedule: "daily"
    commit_message:
       prefix: "[FF-1429]" 
    default_reviewers:
       - "credfeto"
    default_assignees:
       - "credfeto"

