name: sqlcheck workflow
on: pull_request

jobs:
  sqlcheck:
    name: sqlcheck job 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: yokawasa/action-sqlcheck@v1.1.0
      with:
        post-comment: true
        risk-level: 1
        verbose: true
        token: ${{ secrets.GITHUB_TOKEN }}