name: Update Labels

on:
  push:
    branches:
    - master
    paths:
    - '.github/labels.yml'
    - '.github/workflows/update-labels.yml'

jobs:
  update-labels-config:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
        token: ${{ secrets.SOURCE_PUSH_TOKEN }}
    - if: success()
      uses: crazy-max/ghaction-github-labeler@v3
      with:
        github-token: ${{ secrets.SOURCE_PUSH_TOKEN }}
        yaml-file: .github/labels.yml
        skip-delete: true
        dry-run: false
        exclude: |
          help*
          *issue