name: Update Labels

on:
  push:
    branches:
    - master
    paths:
    - '.github/labels.yml'
    - '.github/workflows/update-labels.yml'

jobs:
  update-labels-config:

    runs-on: [self-hosted, linux]

    steps:
    - run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.SOURCE_PUSH_TOKEN }}
    - if: success()
      uses: crazy-max/ghaction-github-labeler@v3.1.1
      with:
        github-token: ${{ secrets.SOURCE_PUSH_TOKEN }}
        yaml-file: .github/labels.yml
        skip-delete: true
        dry-run: false
        exclude: |
          help*
          *issue
    - uses: colpal/actions-clean@v1
      if: ${{ always() }} # To ensure this step runs even when earlier steps fail
